# Generated by Django 4.2.16 on 2024-09-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boost_id",
                    models.CharField(max_length=100, verbose_name="id бонуса"),
                ),
                (
                    "boost_type",
                    models.CharField(max_length=100, verbose_name="Тип бонуса"),
                ),
            ],
            options={
                "verbose_name": "Игровой бонус",
                "verbose_name_plural": "Игровые бонусы",
                "ordering": ["boost_type"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.CharField(max_length=100, verbose_name="id игрока"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя игрока")),
                (
                    "entrance_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Время входа игрока"
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerBoost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ice.boost",
                        verbose_name="Бонусы участника",
                    ),
                ),
                (
                    "player_boost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ice.player",
                        verbose_name="Участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полученый игровой бонус",
                "verbose_name_plural": "Полученые игровые бонусы",
                "ordering": ["player_boost"],
            },
        ),
        migrations.AddField(
            model_name="boost",
            name="player",
            field=models.ManyToManyField(
                related_name="pleer",
                through="ice.PlayerBoost",
                to="ice.player",
                verbose_name="Владелец бонуса",
            ),
        ),
    ]
